version: '3'
services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/hilmi_database
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017